/**
 * Visible explanatory copy (N5) — the app's hints, empty states, errors and
 * one-line intros. EDIT ANY WORD HERE; no component holds this text.
 *
 * The rules these obey are in CLAUDE.md ("Copy rules") and are enforced by
 * copy.test.ts: no visible block over 30 words or two sentences, one idea per
 * sentence, under 20 words a sentence, active voice, reading age about nine.
 * A field gets NO description unless it stops a wrong entry, says where to find
 * the number, or defines a term a beginner will not know.
 *
 * NOT here on purpose: verdict lines, levers and Deal Score headlines (they are
 * generated by @gil-bricks/core and naming the binding number IS the plain
 * English win); tooltips (src/content/microcopy.ts) and show-the-maths bodies,
 * which are where longer explanation belongs; legal and licence attributions.
 */
export const COPY = {
  /** The analyser shell: what to do first, and what went wrong. */
  analyser: {
    startSubject: 'Start with the postcode, price and property type.',
    startComps: 'Start with a postcode to see nearby sold prices.',
    outsideEnglandWales: 'We only have sold prices for England and Wales.',
    loadFailed: 'We couldn’t load sold prices. Try again in a moment.',
    loadFailedTitle: 'Couldn’t load the sales data',
    noVerdictYet: 'No verdict for this strategy yet. The comps and valuation below still work.',
    fromExtension: 'Brought over from the extension — everything’s filled in below.',
    backToInputs: 'Back to inputs',
  },
  /** What each strategy needs before it can answer, and what it warns about. */
  verdict: {
    inputsClash: 'These numbers don’t work together. Check your inputs.',
    needRent: 'Add the monthly rent to get a verdict.',
    needRoomRent: 'Add the rent per room to get a verdict.',
    needFlip: 'Add the refurb budget and the sale price after works.',
    needBrrrr: 'Add the end value and the rent after works.',
    needLtv: 'Enter your custom loan-to-value % to get a verdict.',
    prefilled: 'Pre-filled from our estimate. Raise it only if your finish will beat local stock.',
    companyTax: 'Companies always pay the higher purchase-tax rates — applied for you.',
    flipTax: 'Flip profit is usually taxed as trading income, not capital gains. Check with an accountant.',
    hmoScope: 'For small HMOs, up to 6 people. It won’t value a commercial HMO — that needs a surveyor.',
    hmoSuiGeneris: '7 or more people is a large ‘sui generis’ HMO — outside this tool.',
    hmoBills: 'Tenants paying their own bills usually cuts costs. Lower the operating % to match.',
    hmoRegister: 'Search your council’s site for its HMO register.',
  },
  /** What it's worth: the states where we cannot show a number yet. */
  valuation: {
    lrTimeoutTitle: 'Sale history unavailable',
    lrTimeout: 'We couldn’t reach HM Land Registry. The estimate below still uses nearby sold prices.',
    needAreaTitle: 'Add the floor area for £/sqft',
    needArea: 'Add the internal area to see £ per square foot. It’s on the EPC.',
    thinEvidence: 'Not enough evidence yet. Add the internal area, or a house number.',
    contextOnly: 'Beds, baths, garden and parking are context only.',
  },
  /** The comparables module and its map. */
  comps: {
    waiting: 'Waiting for a postcode…',
    noneTitle: 'No matching sales',
    none: 'No sold prices matched this search near this postcode.',
    untick: 'Untick a row to leave it out — the stats update instantly.',
    listCarriesData: 'The list view carries the same data for keyboard and screen-reader use.',
    article4: 'Article 4 areas from the national planning dataset (England). Coverage is patchy — check with the council.',
  },
  /** Area Data: the honest limits of each panel, in one line each. */
  area: {
    thinMarket: 'That usually means a thin market, not a bad postcode.',
    thinMarketCta: 'Browse sold comparables within a mile',
    wideSweep: 'Comparing with everything sold within a mile — this takes a moment.',
    /** Interpolated with the country the index is actually for — it is an
     * England index or a Wales index, never a UK one. */
    hpiScope: (country: string): string => `A ${country}-wide index, not a local one. The sold prices above are the better guide.`,
    hpiUnavailable: 'The house-price trend isn’t available right now. Use the sold prices above.',
    deprivationScope: 'An official score for small areas, not for any one street.',
    deprivationMissing: 'No deprivation score for this postcode sector. Everything else still holds.',
    crimeScope: 'Counts only, and no judgement about any street. Some forces publish incomplete street data.',
    crimeHalfMile: 'The full 1-mile list was too big, so these cover about half a mile.',
    /** The Environment Agency's prescribed acknowledgement — attribution, not
     * copy: it is quoted, never trimmed. */
    floodSource: 'Uses Environment Agency flood and river level data from the real-time data API (Beta).',
  },
  /** Signing in, saving, and the deals board. */
  account: {
    signInToSave: 'Your saved deals live here once you sign in. It’s free and takes one tap.',
    signedUp: 'You’re on the list. Untick any time.',
    deleteWarning: 'Deletes your account and saved deals, and unsubscribes you. This can’t be undone.',
    loginWhy: 'Free forever — sign in to save deals and share them.',
    cookiesOff: 'Signing in needs cookies switched on. Your analysis stays in this link — copy it.',
    checkFailed: 'The human check didn’t load. Signing in still works; a new account needs it — reload to retry.',
    dealsSignIn: 'Your deals live here once you sign in. It’s free and takes one tap.',
    dealsEmpty: 'Deals arrive when you analyse a listing. There’s no “add a property” button by design.',
    dealsEmptyCta: 'Open an analyser',
    auctionWarning: 'Auction — read the legal pack before you bid.',
  },
  /** The Chrome side panel. The badge itself is Google's artwork, unmodified;
   * only the words around it are ours. */
  extension: {
    badgeAlt: 'Available in the Chrome Web Store',
    desktopNote: 'Chrome on a desktop or laptop. It isn’t available on phones.',
    homeLead: 'On a computer? The free Chrome side panel scores any Rightmove or Zoopla listing as you browse.',
    seeMore: 'See what it does',
  },
  /** One sold record. */
  transaction: {
    noId: 'This link doesn’t point to a sale. Go back and pick a row.',
    failed: 'We couldn’t load this sold record. Try again in a moment.',
    failedTitle: 'We couldn’t show this sale',
  },
} as const;
